admin-portal/config/routes.rb
Rails.application.routes.draw do

  # Reports
  get 'log/product_api', to: 'log#product_api'
  get 'log/client_api', to: 'log#client_api'
  get 'log/approval', to: 'log#approval'
  get 'log/session_history', to: 'log#session_history'


  # Insurer Product API
  get 'insurer/:insurer_id/api/new', to: 'insurer_product_api#new'
  post 'insurer/:insurer_id/api/create', to: 'insurer_product_api#create'
  get 'insurer/:insurer_id/api/edit/:id', to: 'insurer_product_api#edit'
  get 'insurer/:insurer_id/api/edit_pending/:approval_id', to: 'insurer_product_api#edit_pending'
  post 'insurer/:insurer_id/api/update_pending/:approval_id', to: 'insurer_product_api#update_pending'
  match 'insurer/:insurer_id/api/update/:id', to: 'insurer_product_api#update', via: %i[patch post]
  get 'insurer/:insurer_id/api/delete/:id', to: 'insurer_product_api#delete'
  get 'insurer/:insurer_id/api/approve/:id', to: 'insurer_product_api#approve'
  get 'insurer/:insurer_id/api/approve_create/:approval_id', to: 'insurer_product_api#approve_create'
  get 'insurer/:insurer_id/api/reject/:id', to: 'insurer_product_api#reject'
  get 'insurer/:insurer_id/api/reject_delete/:approval_id', to: 'insurer_product_api#reject_delete'

  # Insurer Mapping
  get 'insurer/:insurer_id/mapping/new', to: 'insurer_mapping#new'
  post 'insurer/:insurer_id/mapping/create', to: 'insurer_mapping#create'
  get 'insurer/:insurer_id/mapping/edit/:id', to: 'insurer_mapping#edit'
  post 'insurer/:insurer_id/mapping/update/:id', to: 'insurer_mapping#update'
  get 'insurer/:insurer_id/mapping/delete/:id', to: 'insurer_mapping#delete'

  # Insurer
  get 'insurer/list', to: 'insurer#list'
  get 'insurer/new', to: 'insurer#new'
  post 'insurer/create', to: 'insurer#create'
  get 'insurer/edit/:id', to: 'insurer#edit'
  get 'insurer/edit_pending/:approval_id', to: 'insurer#edit_pending'
  post 'insurer/update_pending/:approval_id', to: 'insurer#update_pending'
  patch 'insurer/update/:id', to: 'insurer#update'
  get 'insurer/delete/:id', to: 'insurer#delete'
  get 'insurer/approve/:id', to: 'insurer#approve'
  get 'insurer/approve_create/:approval_id', to: 'insurer#approve_create'
  get 'insurer/reject/:id', to: 'insurer#reject'
  get 'insurer/reject_delete/:approval_id', to: 'insurer#reject_delete'

  # Mapping
  get 'mapping/list', to: 'mapping#list'
  get 'mapping/new', to: 'mapping#new'
  post 'mapping/create', to: 'mapping#create'
  get 'mapping/edit/:id', to: 'mapping#edit'
  get 'mapping/edit_pending/:approval_id', to: 'mapping#edit_pending'
  post 'mapping/update_pending/:approval_id', to: 'mapping#update_pending'
  patch 'mapping/update/:id', to: 'mapping#update'
  get 'mapping/delete/:id', to: 'mapping#delete'
  get 'mapping/approve/:id', to: 'mapping#approve'
  get 'mapping/approve_create/:approval_id', to: 'mapping#approve_create'
  get 'mapping/reject/:id', to: 'mapping#reject'
  get 'mapping/reject_delete/:approval_id', to: 'mapping#reject_delete'

  # Client
  get 'client/list', to: 'client#list'
  get 'client/new', to: 'client#new'
  post 'client/create', to: 'client#create'
  get 'client/edit/:id', to: 'client#edit'
  get 'client/edit_pending/:approval_id', to: 'client#edit_pending'
  post 'client/update_pending/:approval_id', to: 'client#update_pending'
  get 'client/reset_api_key_pending/:approval_id', to: 'client#reset_api_key_pending'
  patch 'client/update/:id', to: 'client#update'
  get 'client/delete/:id', to: 'client#delete'
  get 'client/approve/:id', to: 'client#approve'
  get 'client/approve_create/:approval_id', to: 'client#approve_create'
  get 'client/reject/:id', to: 'client#reject'
  get 'client/reject_delete/:approval_id', to: 'client#reject_delete'
  get 'client/reset_api_key/:id', to: 'client#reset_api_key'

  # Product
  get 'product/list', to: 'product#list'
  get 'product/new', to: 'product#new'
  post 'product/create', to: 'product#create'
  get 'product/edit/:id', to: 'product#edit'
  get 'product/edit_pending/:approval_id', to: 'product#edit_pending'
  get 'product/delete_pending/:approval_id', to: 'product#delete_pending'
  post 'product/update_pending/:approval_id', to: 'product#update_pending'
  patch 'product/update/:id', to: 'product#update'
  get 'product/approve/:id', to: 'product#approve'
  get 'product/reject/:id', to: 'product#reject'
  get 'product/approve_create/:approval_id', to: 'product#approve_create'
  get 'product/reject_delete/:approval_id', to: 'product#reject_delete'
  get 'product/delete/:id', to: 'product#delete'

  # client api
  get 'client/api/list', to: 'client_api#list'
  get 'client/api/new', to: 'client_api#new'
  get 'client/api/edit/:id', to: 'client_api#edit'
  get 'client/api/edit_pending/:approval_id', to: 'client_api#edit_pending'
  get 'client/api/delete_pending/:approval_id', to: 'client_api#delete_pending'
  post 'client/api/update_pending/:approval_id', to: 'client_api#update_pending'
  post 'client/api/create', to: 'client_api#create'
  patch 'client/api/update/:id', to: 'client_api#update'
  get 'client/api/approve/:id', to: 'client_api#approve'
  get 'client/api/reject/:id', to: 'client_api#reject'
  get 'client/api/approve_create/:approval_id', to: 'client_api#approve_create'
  get 'client/api/reject_delete/:approval_id', to: 'client_api#reject_delete'
  get 'client/api/delete/:id', to: 'client_api#delete'

  # dashboard
  root 'dashboard#main'
  get  '/setup', to: 'dashboard#setup'
  post '/setup_submit', to: 'dashboard#setup_submit'
  get '/profile', to: 'dashboard#profile'
  post '/profile_submit', to: 'dashboard#profile_submit'
  get '/setting', to: 'dashboard#setting'
  post '/setting_submit', to: 'dashboard#setting_submit'


  # authentication
  get 'login', to: 'authentication#login'
  get 'logout', to: 'authentication#logout'
  get 'password/forgot', to: 'authentication#forgot_password'
  get 'password/reset/:token', to: 'authentication#reset_password'
  get 'invite/:token', to: 'authentication#invite'
  post 'password/forgot/submit', to: 'authentication#forgot_password_submit'
  post 'password/reset/submit', to: 'authentication#reset_password_submit'
  post 'login/submit', to: 'authentication#login_submit'
  post 'invite_submit', to: 'authentication#invite_submit'

  # user
  get 'user/list', to: 'user#list'
  get 'user/new', to: 'user#new'
  post 'user/create', to: 'user#create'
  get 'user/edit/:id', to: 'user#edit'
  patch 'user/update/:id', to: 'user#update'
  get 'user/delete/:id', to: 'user#delete'
end

admin-portal/app/controllers/mapping_controller.rb
class MappingController < ApplicationController

  before_action :redirect_not_admin, only: %i[approve approve_create reject reject_delete]
  before_action :redirect_cannot_delete, only: %i[delete]

  add_breadcrumb 'Mapping', :mapping_list_path

  def list
    @mappings = Mapping.where(status: true).order('created_at desc')
    @mapping_pendings = Approval.where(table: 'MAPPING').where(row_id: nil)
  end

  def new
    @mapping = Mapping.new
    add_breadcrumb 'New'
  end

  def create
    Approval.create(table: 'MAPPING', content:  mapping_params.to_json, user: current_user.id)
    flash[:success] = 'Success create new Mapping'
    redirect_to mapping_list_path
  end

  def edit_pending

    @mapping = Mapping.new
    @approval = Approval.find(params[:approval_id])
    flash.now[:alert] = "This new Mapping is yet to be approved. What would you want to do? <a href='/mapping/approve_create/#{@approval.id}'><strong>APPROVE</strong></a> | <a href='/mapping/reject_delete/#{@approval.id}'><strong>REJECT</strong></></a>".html_safe if can_approve_reject_deactivate

    # api cache is not exist
    if @approval.nil?
      redirect_to mapping_list_path
      return
    end

    @mapping_pending = JSON.parse(@approval.content)
    add_breadcrumb @mapping_pending['name']

  end

  def update_pending
    approval = Approval.find(params[:approval_id])
    approval.update(content: mapping_params.to_json, user: current_user.id)

    flash[:success] = 'Save changes Mapping'
    redirect_to "/mapping/edit_pending/#{approval.id}"
  end

  def edit
    @mapping = Mapping.find(params[:id])
    approval = Approval.where(table: 'MAPPING').where(row_id: @mapping.id)
    @is_pending = false
    if approval.any?
      flash.now[:alert] = "This Mapping is yet to be approved. What would you want to do? <a href='/mapping/approve/#{@mapping.id}'><strong>APPROVE</strong></a> | <a href='/mapping/reject/#{@mapping.id}'><strong>REJECT</strong></></a>".html_safe if can_approve_reject_deactivate
      @mapping_pendings = JSON.parse(approval.first.content)
      @is_pending = true
    end
    add_breadcrumb @mapping.name
  end

  def update
    mapping = Mapping.find(params[:id])

    # get approval
    approval = Approval.where(table: 'MAPPING').where(row_id: mapping.id)

    if approval.any?
      approval.first.update(content: mapping_params.to_json, user: current_user.id)
    else
      Approval.create(
        table: 'MAPPING',
        row_id: mapping.id,
        content: mapping_params.to_json,
        user: current_user.id
      )
    end

    flash[:success] = 'Save changes Mapping'
    redirect_to "/mapping/edit/#{mapping.id}"
  end

  def delete
    mapping = Mapping.find(params[:id])
    mapping.update(status: false)
    flash[:success] = 'Deleted Mapping'
    redirect_to mapping_list_path
  end

  def approve
    mapping = Mapping.find(params[:id])
    approval = Approval.where(table:'MAPPING').find_by_row_id(mapping.id)
    mapping.update(JSON.parse(approval.content))

    unless mapping.save
      flash[:error] = 'Somethings wrong. Try again.'
    else

      # send to author
      author = User.find(approval.user)
      if author.role_id == 3
        ApprovalMailer.delay.approve_update(author, "approved", current_user.name, "Mapping List",  mapping.name)
      end
      # send to admin
      User.where(role_id: 1..2).where(status: true).where(activation_status: true).each do |user|
        ApprovalMailer.delay.approve_update(user, "approved", current_user.name, "Mapping List",  mapping.name)
      end
      approval.destroy
      flash[:success] = 'Save changes Mapping is approved.'
    end

    redirect_to "/mapping/edit/#{mapping.id}"
  end

  def approve_create
    approval = Approval.find(params[:approval_id])

    if approval.nil?
      redirect_to mapping_list_path
      return
    end

    mapping = Mapping.create(JSON.parse(approval.content))

    unless mapping.save
      flash[:error] = 'Somethings wrong. Please try again'
      redirect_to "/mapping/edit_pending/#{approval.id}"
      return
    end

    # send to author
    author = User.find(approval.user)
    if author.role_id == 3
      ApprovalMailer.delay.approve_create(author, "approved", current_user.name, "Mapping List")
    end
    # send to admin
    User.where(role_id: 1..2).where(status: true).where(activation_status: true).each do |user|
      ApprovalMailer.delay.approve_create(user, "approved", current_user.name, "Mapping List")
    end
    approval.destroy

    flash[:success] = 'Create new Mapping is approved.'
    redirect_to "/mapping/edit/#{mapping.id}"
  end

  def reject
    mapping = Mapping.find(params[:id])
    approval = Approval.where(table:'MAPPING').find_by_row_id(mapping.id)

    # send to author
    author = User.find(approval.user)
    if author.role_id == 3
      ApprovalMailer.delay.approve_update(author, "rejected", current_user.name, "Mapping List",  mapping.name)
    end
    # send to admin
    User.where(role_id: 1..2).where(status: true).where(activation_status: true).each do |user|
      ApprovalMailer.delay.approve_update(user, "rejected", current_user.name, "Mapping List",  mapping.name)
    end
    approval.destroy
    flash[:success] = 'Save changes Mapping is rejected.'
    redirect_to "/mapping/edit/#{mapping.id}"
  end

  def reject_delete

    approval = Approval.find(params[:approval_id])

    if approval.nil?
      redirect_to mapping_list_path
      return
    end

    # send to author
    author = User.find(approval.user)
    if author.role_id == 3
      ApprovalMailer.delay.approve_create(author, "rejected", current_user.name, "Mapping List")
    end
    # send to admin
    User.where(role_id: 1..2).where(status: true).where(activation_status: true).each do |user|
      ApprovalMailer.delay.approve_create(user, "rejected", current_user.name, "Mapping List")
    end
    approval.destroy

    flash[:success] = 'Pending Mapping is rejected.'
    redirect_to mapping_list_path
  end

  private

  def mapping_params
    params.require(:mapping).permit(:name, :list)
  end
end

admin-portal/app/helpers/mapping_helper.rb
module MappingHelper
end

admin-portal/app/views/mapping/_mapping_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for  @mapping, url: {action: action_name == 'new' ? 'create' : 'update'}, html: { class: 'form' } do |f| %>
      <div class="form-group <%= @is_pending && @mapping_pendings["name"] != @mapping.name ? "alert alert-warning".html_safe : nil%> ">
        <%= f.label :name do %>
          Name: <span>&#42;</span>
        <% end %>
        <%= f.text_field :name, value: !@is_pending ? @mapping.name : @mapping_pendings["name"], class: 'form-control', required: true %>
        <% if @is_pending && @mapping_pendings["name"] != @mapping.name  %>
          <span id="helpBlock" class="help-block">Current Value: <%= @mapping.name %></span>
        <% end %>
      </div>
      <div class="form-group <%= @is_pending && @mapping_pendings["list"] != @mapping.list ? "alert alert-warning".html_safe : nil%> ">
        <%= f.label :list do %>
          Values: <span>&#42;</span>
        <% end %>
        <p><em>Enter values separated with new line</em></p>
        <%= f.text_area :list, value: !@is_pending ? @mapping.list : @mapping_pendings["list"], class: 'form-control', required: true, rows: 3 %>
        <% if @is_pending && @mapping_pendings["list"] != @mapping.list  %>
          <span id="helpBlock" class="help-block">Current Value: <%= @mapping.list %></span>
        <% end %>
      </div>

      <%= f.submit action_name == 'new' ? 'Submit' : 'Save Changes', class: 'btn btn-success' %>

      <%= link_to 'Cancel', mapping_list_path, class: 'btn btn-warning' %>
    <% end %>

    <% if action_name == 'edit' && is_super_admin %>
      <p class='delete-button'><a href = "/mapping/delete/<%= @mapping.id %>" class="btn btn-danger" >Delete this Mapping</a></p>
    <% end %>
  </div>
</div>

admin-portal/app/views/mapping/edit.html.erb
<!--<h3>Manage Mapping > Edit Mapping</h3>-->
<%= render 'mapping_form'%>

admin-portal/app/views/mapping/edit_pending.html.erb
<!--<h3>Manage Mappings > Edit Mapping</h3>-->
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for  @mapping, url: {action: "update_pending"}, html: { class: 'form' } do |f| %>
      <div class="form-group">
        <%= f.label :name do %>
          Name: <span>&#42;</span>
        <% end %>
        <%= f.text_field :name, value: @mapping_pending["name"], class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label :list do %>
          Values: <span>&#42;</span>
        <% end %>
        <p><em>Enter values separated with new line</em></p>
        <%= f.text_area :list, value: @mapping_pending["list"], class: 'form-control', required: true, rows: 3 %>
      </div>

      <%= f.submit 'Save Changes', class: 'btn btn-success' %>
      <%= link_to 'Cancel', mapping_list_path, class: 'btn btn-warning' %>
    <% end %>
  </div>
</div>

admin-portal/app/views/mapping/list.html.erb
<!--<h3>Manage Mapping</h3>-->
<table id="client_list" class="cell-border <%= @mapping_pendings.blank? && @mappings.blank? ? nil : "css-serial" %>">
  <thead>
  <tr>
    <th>#</th>
    <th width="70%" >Name</th>
    <th># of Items</th>
    <th>Edit</th>
  </tr>
  </thead>
  <tbody>
  <% @mapping_pendings.each do |pending| %>
    <tr>
      <td ></td>
      <td><%= fa_icon('exclamation-circle', type: :solid, style: "color:red;") %> <%= pending.parse_content['name'] %></td>
      <td><%= pending.mapping_count_list %></td>
      <td><a href="/mapping/edit_pending/<%= pending.id %>"><%= fa_icon('edit', type: :solid) %></td>
    </tr>
  <% end %>
  <% @mappings.each_with_index do |map,index| %>
    <tr>
      <td ></td>
      <td><%=  Approval.where(table: 'MAPPING').where(row_id: map.id).any? ? fa_icon('exclamation-circle', type: :solid, style: "color:red;") : nil %> <%= map.name %></td>
      <td><%= map.count_item %></td>
      <td><a href="/mapping/edit/<%= map.id %>"><%= fa_icon('edit', type: :solid) %></a></td>
    </tr>
  <% end %>
  </tbody>
</table>
<p class="m-t-10"><%= link_to 'Add New', mapping_new_path, class: 'btn btn-success' %></p>

admin-portal/app/views/mapping/new.html.erb
<!--<h3>Manage Mapping > Add New Mapping</h3>-->
<%= render 'mapping_form'%>