admin-portal/config/routes.rb
Rails.application.routes.draw do

  # Reports
  get 'log/product_api', to: 'log#product_api'
  get 'log/client_api', to: 'log#client_api'
  get 'log/approval', to: 'log#approval'
  get 'log/session_history', to: 'log#session_history'


  # Insurer Product API
  get 'insurer/:insurer_id/api/new', to: 'insurer_product_api#new'
  post 'insurer/:insurer_id/api/create', to: 'insurer_product_api#create'
  get 'insurer/:insurer_id/api/edit/:id', to: 'insurer_product_api#edit'
  get 'insurer/:insurer_id/api/edit_pending/:approval_id', to: 'insurer_product_api#edit_pending'
  post 'insurer/:insurer_id/api/update_pending/:approval_id', to: 'insurer_product_api#update_pending'
  match 'insurer/:insurer_id/api/update/:id', to: 'insurer_product_api#update', via: %i[patch post]
  get 'insurer/:insurer_id/api/delete/:id', to: 'insurer_product_api#delete'
  get 'insurer/:insurer_id/api/approve/:id', to: 'insurer_product_api#approve'
  get 'insurer/:insurer_id/api/approve_create/:approval_id', to: 'insurer_product_api#approve_create'
  get 'insurer/:insurer_id/api/reject/:id', to: 'insurer_product_api#reject'
  get 'insurer/:insurer_id/api/reject_delete/:approval_id', to: 'insurer_product_api#reject_delete'

  # Insurer Mapping
  get 'insurer/:insurer_id/mapping/new', to: 'insurer_mapping#new'
  post 'insurer/:insurer_id/mapping/create', to: 'insurer_mapping#create'
  get 'insurer/:insurer_id/mapping/edit/:id', to: 'insurer_mapping#edit'
  post 'insurer/:insurer_id/mapping/update/:id', to: 'insurer_mapping#update'
  get 'insurer/:insurer_id/mapping/delete/:id', to: 'insurer_mapping#delete'

  # Insurer
  get 'insurer/list', to: 'insurer#list'
  get 'insurer/new', to: 'insurer#new'
  post 'insurer/create', to: 'insurer#create'
  get 'insurer/edit/:id', to: 'insurer#edit'
  get 'insurer/edit_pending/:approval_id', to: 'insurer#edit_pending'
  post 'insurer/update_pending/:approval_id', to: 'insurer#update_pending'
  patch 'insurer/update/:id', to: 'insurer#update'
  get 'insurer/delete/:id', to: 'insurer#delete'
  get 'insurer/approve/:id', to: 'insurer#approve'
  get 'insurer/approve_create/:approval_id', to: 'insurer#approve_create'
  get 'insurer/reject/:id', to: 'insurer#reject'
  get 'insurer/reject_delete/:approval_id', to: 'insurer#reject_delete'

  # Mapping
  get 'mapping/list', to: 'mapping#list'
  get 'mapping/new', to: 'mapping#new'
  post 'mapping/create', to: 'mapping#create'
  get 'mapping/edit/:id', to: 'mapping#edit'
  get 'mapping/edit_pending/:approval_id', to: 'mapping#edit_pending'
  post 'mapping/update_pending/:approval_id', to: 'mapping#update_pending'
  patch 'mapping/update/:id', to: 'mapping#update'
  get 'mapping/delete/:id', to: 'mapping#delete'
  get 'mapping/approve/:id', to: 'mapping#approve'
  get 'mapping/approve_create/:approval_id', to: 'mapping#approve_create'
  get 'mapping/reject/:id', to: 'mapping#reject'
  get 'mapping/reject_delete/:approval_id', to: 'mapping#reject_delete'

  # Client
  get 'client/list', to: 'client#list'
  get 'client/new', to: 'client#new'
  post 'client/create', to: 'client#create'
  get 'client/edit/:id', to: 'client#edit'
  get 'client/edit_pending/:approval_id', to: 'client#edit_pending'
  post 'client/update_pending/:approval_id', to: 'client#update_pending'
  get 'client/reset_api_key_pending/:approval_id', to: 'client#reset_api_key_pending'
  patch 'client/update/:id', to: 'client#update'
  get 'client/delete/:id', to: 'client#delete'
  get 'client/approve/:id', to: 'client#approve'
  get 'client/approve_create/:approval_id', to: 'client#approve_create'
  get 'client/reject/:id', to: 'client#reject'
  get 'client/reject_delete/:approval_id', to: 'client#reject_delete'
  get 'client/reset_api_key/:id', to: 'client#reset_api_key'

  # Product
  get 'product/list', to: 'product#list'
  get 'product/new', to: 'product#new'
  post 'product/create', to: 'product#create'
  get 'product/edit/:id', to: 'product#edit'
  get 'product/edit_pending/:approval_id', to: 'product#edit_pending'
  get 'product/delete_pending/:approval_id', to: 'product#delete_pending'
  post 'product/update_pending/:approval_id', to: 'product#update_pending'
  patch 'product/update/:id', to: 'product#update'
  get 'product/approve/:id', to: 'product#approve'
  get 'product/reject/:id', to: 'product#reject'
  get 'product/approve_create/:approval_id', to: 'product#approve_create'
  get 'product/reject_delete/:approval_id', to: 'product#reject_delete'
  get 'product/delete/:id', to: 'product#delete'

  # client api
  get 'client/api/list', to: 'client_api#list'
  get 'client/api/new', to: 'client_api#new'
  get 'client/api/edit/:id', to: 'client_api#edit'
  get 'client/api/edit_pending/:approval_id', to: 'client_api#edit_pending'
  get 'client/api/delete_pending/:approval_id', to: 'client_api#delete_pending'
  post 'client/api/update_pending/:approval_id', to: 'client_api#update_pending'
  post 'client/api/create', to: 'client_api#create'
  patch 'client/api/update/:id', to: 'client_api#update'
  get 'client/api/approve/:id', to: 'client_api#approve'
  get 'client/api/reject/:id', to: 'client_api#reject'
  get 'client/api/approve_create/:approval_id', to: 'client_api#approve_create'
  get 'client/api/reject_delete/:approval_id', to: 'client_api#reject_delete'
  get 'client/api/delete/:id', to: 'client_api#delete'

  # dashboard
  root 'dashboard#main'
  get  '/setup', to: 'dashboard#setup'
  post '/setup_submit', to: 'dashboard#setup_submit'
  get '/profile', to: 'dashboard#profile'
  post '/profile_submit', to: 'dashboard#profile_submit'
  get '/setting', to: 'dashboard#setting'
  post '/setting_submit', to: 'dashboard#setting_submit'


  # authentication
  get 'login', to: 'authentication#login'
  get 'logout', to: 'authentication#logout'
  get 'password/forgot', to: 'authentication#forgot_password'
  get 'password/reset/:token', to: 'authentication#reset_password'
  get 'invite/:token', to: 'authentication#invite'
  post 'password/forgot/submit', to: 'authentication#forgot_password_submit'
  post 'password/reset/submit', to: 'authentication#reset_password_submit'
  post 'login/submit', to: 'authentication#login_submit'
  post 'invite_submit', to: 'authentication#invite_submit'

  # user
  get 'user/list', to: 'user#list'
  get 'user/new', to: 'user#new'
  post 'user/create', to: 'user#create'
  get 'user/edit/:id', to: 'user#edit'
  patch 'user/update/:id', to: 'user#update'
  get 'user/delete/:id', to: 'user#delete'
end

admin-portal/app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  before_action :authenticate, except: %i[login login_submit logout forgot_password forgot_password_submit reset_password reset_password_submit invite invite_submit]

  def login; end

  def login_submit

    user = User.find_by_email(params[:email])

    if user.nil?
      flash[:error] = 'Sorry, invalid email!'
      redirect_to login_path
      return
    end

    unless user.status
      flash[:error] = 'Sorry, this account has been deleted'
      redirect_to login_path
      return
    end

    unless user.accept_invitation
      flash[:error] = 'Sorry, this account must accept invitation before login'
      redirect_to login_path
      return
    end

    unless user.activation_status
      flash[:error] = 'Sorry, this account has been deactivated'
      redirect_to login_path
      return
    end

    if user.password == params[:password]

      # update previous session status to false
      previous_session = Session.where(user_id: user.id)
      if previous_session.any?
        previous_session.last.update(status: false)
      end

      user_agent = UserAgent.parse(request.user_agent)
      # create session
      user_session = Session.create(
                 user_id: user.id,
                 platform: user_agent.platform,
                 browser: user_agent.browser,
                 ip_address: request.remote_ip,
                 version: user_agent.version,
                 expired_at: Time.now + Setting.find_by_type_name('SESSION_WEB').value.to_i.minutes
      )

      session[:id] = user_session.id
      # session[:user_last_seen] = Time.now
      session[:user_id] = user.id

      redirect_to root_path
      return
    else
      flash[:error] = "Sorry, invalid password!"
      redirect_to login_path
    end
  end

  def logout
    user_session = Session.find(session[:id])

    unless user_session.nil?
      user_session.update(status: false)
      session.delete(:user_id)
      session.delete(:id)
      session.delete(:user_last_seen)
      session.delete(:login_at)
      reset_session
    end

    redirect_to root_path
  end

  def forgot_password; end

  def forgot_password_submit
    user = User.find_by_email(params[:email])

    if user.nil?
      flash[:error] = 'Sorry, invalid email!'
      redirect_to password_forgot_path
      return
    end

    unless user.status
      flash[:error] = 'Sorry, this account has been deleted!'
      redirect_to password_forgot_path
      return
    end

    unless user.accept_invitation
      flash[:error] = 'Sorry, this account must accept invitation first!'
      redirect_to password_forgot_path
      return
    end

    unless user.activation_status
      flash[:error] = 'Sorry, this account has been deactivated!'
      redirect_to password_forgot_path
      return
    end

    user.reset_password
    # send email
    AuthenticationMailer.delay.reseting_password(user, request.base_url)

    flash[:notice] = 'A link has send to your email to reset your password'
    redirect_to password_forgot_path

  end

  def reset_password

    if params[:token].nil?
      redirect_to root_path
      return
    end

    @user = User.find_by(reset_password_token: params[:token])

    if @user.nil?
      redirect_to root_path
      return
    end

    if (@user.reset_password_send_at + 24.hours) < Time.now
      flash[:alert] = 'Reset password token has expired.'
      redirect_to root_path
      return
    end


  end

  def reset_password_submit

    if params[:token].nil?
      redirect_to root_path
      return
    end

    user = User.find_by_reset_password_token(params[:token])

    if user.nil?
      flash[:error] = 'User not exist!'
      redirect_to root_path
      return
    end

    unless user.status
      flash[:error] = 'Sorry, this account has been deleted!'
      redirect_to root_path
      return
    end

    unless user.accept_invitation
      flash[:error] = 'Sorry, this account must accept invitation first!'
      redirect_to root_path
      return
    end

    unless user.activation_status
      flash[:error] = 'Sorry, this account has been deactivated!'
      redirect_to root_path
      return
    end


    if params[:password] != params[:repeat_password]
      flash[:error] = 'Password and Repeat password is not equal!'
      redirect_to "/password/reset/#{user.reset_password_token}"
      return
    end

    user.update(
            password_hash: BCrypt::Password.create(params[:password]),
            reset_password_token: nil,
            reset_password_send_at: nil
    )
    flash[:success] = 'Succesfuly reset your password.'
    redirect_to login_path

  end

  def invite

    @user = User.find_by_invitation_token(params[:token])

    if @user.nil?
      flash[:error] = 'Invalid link'
      redirect_to root_path
      return
    end

    unless @user.status
      flash[:error] = 'Sorry, this account has been deleted'
      redirect_to root_path
      return
    end

    if (@user.invitation_send_at + 24.hours) < Time.now
      flash[:alert] = 'Invitation token has expired.'
      redirect_to root_path
      return
    end

  end

  def invite_submit
    user = User.find_by_invitation_token(params[:token])

    if user.nil?
      flash[:error] = 'Invalid link'
      redirect_to root_path
      return
    end

    if params[:password] != params[:repeat_password]
      flash[:error] = 'Password and Repeat password is not equal!'
      redirect_to "/invite/#{user.invitation_token}"
      return
    end

    user.update(
            name: params[:name],
            password_hash: BCrypt::Password.create(params[:password]),
            activation_status: true,
            accept_invitation: true,
            invitation_token: nil,
            invitation_send_at: nil
    )

    flash[:success] = 'Success create account. Login to proceed'

    unless session[:id].nil?
      redirect_to logout_path
    else
      redirect_to root_path
    end
  end
end

admin-portal/app/helpers/authentication_helper.rb
module AuthenticationHelper
end

admin-portal/app/views/authentication/forgot_password.html.erb
<div class="container">

  <%= form_tag(password_forgot_submit_path, {class:'form-signin'}) do %>
    <div><%= flash_messages %></div>
    <h3>Enter your email address</h3>
    <%= label_tag(:email, "Search for:", class: 'sr-only') %>
    <%= email_field_tag(:email, nil, class: 'form-control', placeholder: "Email Address", required: true, autofocus: true )%>
    <br />
    <%= submit_tag("Continue", class: 'btn btn-lg btn-primary btn-block') %>
    <a href="/login" style="margin-top: 115px;">Back to login page</a>
<% end %>

</div> <!-- /container -->

admin-portal/app/views/authentication/invite.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div><%= flash_messages %></div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Create Account</h3>
      </div>
      <div class="panel-body">
        <%= form_tag(invite_submit_path, {class:'form'}) do %>
          <%= hidden_field_tag(:token, @user.invitation_token, class: 'form-control', required: true ) %>
          <div class="form-group">
            <%= label_tag :name do %>
              Name: <span>&#42;</span>
            <% end %>
            <%= text_field_tag(:name, @user.name, class: 'form-control', placeholder: "", required: true ) %>
          </div>
          <div class="form-group">
            <%= label_tag :email do %>
              E-mail Address: <span>&#42;</span>
            <% end %>
            <%= text_field_tag(:email, @user.email, class: 'form-control', disabled: true) %>
          </div>
          <div class="form-group">
            <%= label_tag :password do %>
              New Password: <span>&#42;</span>
            <% end %>
            <%= password_field_tag(:password, nil, class: 'form-control', placeholder: "", required: true ) %>
          </div>
          <div class="form-group">
            <%= label_tag :repeat_password do %>
              Repeat Password: <span>&#42;</span>
            <% end %>
            <%= password_field_tag(:repeat_password, nil, class: 'form-control', placeholder: "", required: true ) %>
          </div>
          <%= submit_tag("Save", class: 'btn btn-default') %>
        <% end %>
      </div>
    </div>
  </div>
</div>

admin-portal/app/views/authentication/login.html.erb
<div class="container">


  <%= form_tag(login_submit_path, {class:'form-signin'}) do %>
    <div><%= flash_messages %></div>
    <h2 class="form-signin-heading" style="text-align: center">Insurer Market Admin Portal</h2>
    <%= label_tag(:q, "Search for:", class: 'sr-only') %>
    <%= email_field_tag(:email, nil, class: 'form-control', placeholder: "Email Address", required: true, autofocus: true ) %>
    <%= label_tag(:q, "Search for:", class:'sr-only') %>
    <%= password_field_tag(:password, nil, class: 'form-control', placeholder: "Password", required: true) %>
    <div class="checkbox">
    </div>
    <%= submit_tag("Sign in", class: 'btn btn-lg btn-primary btn-block') %>
    <a href="/password/forgot" style="margin-top: 115px;">Forgot your password?</a>

<% end %>


</div>

admin-portal/app/views/authentication/reset_password.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div><%= flash_messages %></div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Reset Password</h3>
      </div>
      <div class="panel-body">
        <%= form_tag(password_reset_submit_path, {class:'form'}) do %>
          <%= hidden_field_tag(:token, @user.reset_password_token, class: 'form-control' ) %>
          <div class="form-group">
            <%= label_tag :password do %>
              New Password: <span>&#42;</span>
            <% end %>
            <%= password_field_tag(:password, nil, class: 'form-control', placeholder: "", required: true ) %>
          </div>
          <div class="form-group">
            <%= label_tag :repeat_password do %>
              Repeat Password: <span>&#42;</span>
            <% end %>
            <%= password_field_tag(:repeat_password, nil, class: 'form-control', placeholder: "", required: true ) %>
          </div>
          <%= submit_tag("Save", class: 'btn btn-default') %>
        <% end %>
      </div>
    </div>
  </div>
</div>